#!/usr/bin/env python
"""
EducAgent Web Platform Launcher
Starts the FastAPI backend and Next.js frontend together.
Usage: python scripts/start_web.py
"""

import os
from pathlib import Path
import shutil
import signal
import subprocess
import sys
import time

from dotenv import load_dotenv

project_root = Path(__file__).parent.parent
load_dotenv(project_root / ".env", override=False)

os.environ["PYTHONUNBUFFERED"] = "1"
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)

if project_root not in sys.path:
    sys.path.insert(0, str(project_root))


def print_flush(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)


def terminate_process_tree(process, name="Process", timeout=5):
    if process is None or process.poll() is not None:
        return

    pid = process.pid
    print_flush(f"Stopping {name} (PID: {pid})...")

    try:
        if os.name == "nt":
            subprocess.run(["taskkill", "/F", "/T", "/PID", str(pid)], check=False,
                           capture_output=True)
            try:
                process.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=2)
        else:
            pgid = os.getpgid(pid)
            try:
                os.killpg(pgid, signal.SIGTERM)
            except ProcessLookupError:
                return
            try:
                process.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                os.killpg(pgid, signal.SIGKILL)
                process.wait(timeout=2)
    except Exception as e:
        print_flush(f"  Warning: error stopping {name}: {e}")


def start_backend():
    from src.services.setup import get_backend_port

    backend_port = get_backend_port(project_root)
    print_flush(f"Starting backend on port {backend_port}...")

    run_server = project_root / "src" / "api" / "run_server.py"
    env = os.environ.copy()
    env.update({"PYTHONIOENCODING": "utf-8", "PYTHONUTF8": "1", "PYTHONUNBUFFERED": "1"})

    kwargs = dict(
        cwd=project_root,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    if os.name != "nt":
        kwargs["start_new_session"] = True
    else:
        kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP

    process = subprocess.Popen([sys.executable, str(run_server)], **kwargs)

    import threading

    def _log():
        for line in iter(process.stdout.readline, ""):
            if line:
                print_flush(f"[Backend] {line.rstrip()}")

    threading.Thread(target=_log, daemon=True).start()
    print_flush(f"Backend started (PID: {process.pid})")
    return process


def start_frontend():
    from src.services.setup import get_backend_port, get_frontend_port

    frontend_port = get_frontend_port(project_root)
    backend_port = get_backend_port(project_root)
    web_dir = project_root / "web"

    npm = shutil.which("npm")
    if not npm:
        raise RuntimeError("npm not found — install Node.js first.")

    api_base = (
        os.environ.get("NEXT_PUBLIC_API_BASE_EXTERNAL")
        or os.environ.get("NEXT_PUBLIC_API_BASE")
        or f"http://localhost:{backend_port}"
    )

    # Write .env.local for Next.js
    (web_dir / ".env.local").write_text(
        f"# Auto-generated by start_web.py\nNEXT_PUBLIC_API_BASE={api_base}\n"
    )

    print_flush(f"Starting frontend on port {frontend_port} (API: {api_base})...")

    env = os.environ.copy()
    env.update({"PORT": str(frontend_port), "NEXT_PUBLIC_API_BASE": api_base})

    kwargs = dict(
        cwd=web_dir,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    if os.name != "nt":
        kwargs["start_new_session"] = True
    else:
        kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP

    process = subprocess.Popen([npm, "run", "dev", "--", "-p", str(frontend_port)], **kwargs)

    import threading

    def _log():
        for line in iter(process.stdout.readline, ""):
            if line:
                print_flush(f"[Frontend] {line.rstrip()}")

    threading.Thread(target=_log, daemon=True).start()
    print_flush(f"Frontend started (PID: {process.pid})")
    return process


if __name__ == "__main__":
    from src.services.setup import get_backend_port, get_frontend_port, init_user_directories

    try:
        init_user_directories(project_root)
    except Exception as e:
        print_flush(f"Warning: could not init user directories: {e}")

    backend = None
    frontend = None

    try:
        backend = start_backend()

        backend_port = get_backend_port(project_root)
        print_flush("Waiting for backend to be ready...")

        import socket

        for _ in range(20):
            time.sleep(1)
            if backend.poll() is not None:
                print_flush(f"Backend exited early (code {backend.returncode}). Check logs above.")
                sys.exit(1)
            try:
                s = socket.create_connection(("localhost", backend_port), timeout=1)
                s.close()
                print_flush(f"Backend ready on port {backend_port}.")
                break
            except OSError:
                pass

        frontend = start_frontend()

        frontend_port = get_frontend_port(project_root)

        print_flush("")
        print_flush("=" * 50)
        print_flush("Services running:")
        print_flush(f"  Backend:  http://localhost:{backend_port}/docs")
        print_flush(f"  Frontend: http://localhost:{frontend_port}")
        print_flush("Press Ctrl+C to stop.")
        print_flush("=" * 50)

        while True:
            if backend.poll() is not None:
                print_flush(f"Backend exited unexpectedly (code {backend.returncode}).")
                break
            time.sleep(1)

    except KeyboardInterrupt:
        print_flush("\nStopping services...")
    except Exception as e:
        print_flush(f"Error: {e}")
    finally:
        terminate_process_tree(backend, "Backend")
        terminate_process_tree(frontend, "Frontend")
        print_flush("All services stopped.")
